pid: tmp/pids/thin.pid
group: v
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 4
address: 0.0.0.0
daemonize: true
user: v
group: staff
socket: /tmp/thin.sock
chdir: /Users/v/Projects/Ruby/Redmine #/usr/local/var/www/redmine